import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";

export interface CounterState {
  status: "" | "loading" | "failed";
  image: string;
  imageArray: string[];
  index: number;
}

const initialState: CounterState = {
  status: "",
  image: "https://images.dog.ceo/breeds/terrier-norwich/n02094258_307.jpg",
  imageArray: [],
  index: -1,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const incrementAsync = createAsyncThunk(
  "dog/random",
  async (dispatch, getState) => {
    return await fetch("https://dog.ceo/api/breeds/image/random")
      .then(function (response) {
        // The response is a Response instance.
        // You parse the data into a useable format using `.json()`
        return response.json();
      })
      .then((data) => {
        // `data` is the parsed version of the JSON returned from the above endpoint.
        return data;
      });
  }
);

export const counterSlice = createSlice({
  name: "counter",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    pervious: (state) => {
      if (state.index > 0) {
        state.index -= 1;
      }
    },
    next: (state) => {
      state.index += 1;
    },
    clear: (state) => {
      state.index = -1;
      state.imageArray = [];
    },
    indexUpdate: (state, action: PayloadAction<number>) => {
      state.index = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = "";
        state.image = action.payload.message;
        state.imageArray.push(action.payload.message);
        // state.index++;
        state.index += 1;
        console.log(action.payload);
      });
  },
});

export const { pervious, next, indexUpdate, clear } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectStatus = (state: RootState) => state.counter.status;
export const selectImageArray = (state: RootState) => state.counter.imageArray;
export const selectIndex = (state: RootState) => state.counter.index;

export default counterSlice.reducer;
